### ISSUE TITLE
Still estimating CAUSE posteriors after 4 hrs

### ISSUE THREAD

**Issue by Xuemin-Wang** [jean997/cause#13] opened 2021-01-27 03:39 UTC
Dear Jean,

CAUSE returned the results for the MR analysis from trait A to B using default settings within about 20 mins. There were 9 unique elements of params_obj$mix_grid$S1 and 9 of params_obj$mix_grid$S2. CAUSE posteriors were estimated using 2062 variants. However, when I tried to estimate the causal relationship from trait B to A, it's still estimating posteriors after more than 4 hours with 4 cores (see images below). The number of unique elements of params_obj$mix_grid$S1 and params_obj$mix_grid$S2 were both 10. There were 1888 variants used in CAUSE posterior estimation.
![image](https://user-images.githubusercontent.com/23228449/105937706-d5543980-60a1-11eb-894a-39e2902125ad.png)
![image](https://user-images.githubusercontent.com/23228449/105937751-eac96380-60a1-11eb-9d2d-428d5458c350.png)

I also tried to run it in HPC. It used as many as 27 cores but still couldn't finish the posteriors estimation after about 4 hours. So I had to kill the job due to too much resource usage. Below is the ganglia graph, which may or may not be helpful for your diagnosis. 
![image](https://user-images.githubusercontent.com/23228449/105938325-17ca4600-60a3-11eb-9913-3449795cced4.png)

Do you have any idea of what might be causing the issue?

Many thanks,
patrick

**Comment by Xuemin-Wang** [comment] 2021-01-27 03:42
I had a look at https://github.com/jean997/cause/issues/9 and https://github.com/jean997/cause/issues/5, but they both didn't provide an solution to my issue. 

many thanks,
patrick

**Comment by jean997** [comment] 2021-01-27 17:57
Can you tell me how many variants you are using to estimate the parameters?

**Comment by Xuemin-Wang** [comment] 2021-01-27 20:48
It's still estimating posteriors on my laptop after one day.

**Comment by jean997** [comment] 2021-01-27 21:00
Yeah that is really long. How many variants did you use to estimate the parameters?

**Comment by jean997** [comment] 2021-01-27 21:02
Ah sorry maybe I misunderstood. The posterior fitting step is taking a long time? That is not usually the long one. Usually the parameter estimation takes the longest.

**Comment by jean997** [comment] 2021-01-27 21:03
Are you able to share your data? You could send me the parameters as an RDS file and the data just for the set of variants you are using to estimate posteriors so it shouldn't be too big. I'm not sure why this is happening for you.

**Comment by Xuemin-Wang** [comment] 2021-01-27 21:28
Hi Jean,

Thanks for your reply.

It's the posterior estimation step that has been taking a long time. It will be great if you can help investigate this issue. Here are the data. [To_JeanM.zip](https://github.com/jean997/cause/files/5883208/To_JeanM.zip)

Many thanks,
patrick

**Comment by ZixiaoWang17** [comment] 2021-11-14 16:35
I met this problem too, the log remained in: 'Estimating CAUSE posteriors using  XX  variants.' for almost 12 hours, and this phenomenon happened in almost 100+ cases.

**Comment by jean997** [comment] 2021-11-15 19:21
Hi Zixao, 
How many variants are you using?

**Comment by ZixiaoWang17** [comment] 2021-11-16 00:07
37 for example

Jean Morrison ***@***.***> 于2021年11月16日周二 上午3:21写道：

**Comment by jean997** [comment] 2021-11-16 19:50
Hmm that is really odd. Would you be willing to share your data so I can see? @Xuemin-Wang I am looking at your example now though its been a while. I am sorry I missed your last message.

**Comment by jean997** [comment] 2021-11-16 20:45
Ok @Xuemin-Wang  and @ZixiaoWang17  I am not sure if you are having the same issue but I have some progress on @Xuemin-Wang 's issue. In that data, it seems that the problem is that the scale of `beta_hat_1` is much different than the scale of `beta_hat_2`. I haven't identified exactly how this is causing an issue yet but it can be resolved by scaling up the estimates and sds for the study with very small estimates. In the case of @Xuemin-Wang 's data, I multiplied `beta_hat_1` and `sd1` by 100. I also scaled up the `S1` column of `params$mix_grid` and this resolved the issue. 

I just pushed an update to the package with some additional print statements for tracking progress. @ZixiaoWang17 can you use this version and see what step it is stalling on. I think if it is the same issue, it should be the "setting range" step. You can also try the scaling trick if your studies have estimates on very different scales. 

I will keep digging and see if I can find an internal fix.

**Comment by jean997** [comment] 2021-11-16 21:22
Ok -- I believe I solved the scale problem. Try the most recent version and see if your issues are resolved.
Jean

**Comment by ZixiaoWang17** [comment] 2021-11-17 02:09
Hi @jean997 ，Thanks for your great work and quick reply! I will give it a try and get back to you soon.

Zixiao

**Comment by ZixiaoWang17** [comment] 2021-11-20 02:39
Hi @jean997 , I checked hundreds of cases and the problem is well solved! Thanks for your great contribution!

**Comment by jean997** [comment] 2021-11-22 01:23
🙌

**Closed by jean997** 2021-11-22 01:23 UTC
