### ISSUE TITLE
CAUSE vs MR

### ISSUE THREAD

**Issue by giuliapontali** [jean997/cause#39] opened 2023-07-13 13:41 UTC
Hi,

I am using CAUSE to confirm the results that I obtained with the MR.
So I used as exposure  the SNPs coming from the MR and then I run CAUSE. Looking at the results it seems that I have some inconsistency.

*Example1*
exposure1 192 instruments I2=0%
After running CAUSE I get:
>sharing better than null;
>causal better than null;
>causal better than sharing

but there should not be pleiotropy.

Thanks.

**Comment by jean997** [comment] 2023-07-18 16:36
Sorry I am not sure what your question is. Can you be more specific?

**Comment by giuliapontali** [comment] 2023-07-19 07:04
Hi, 

I would like to test if CAUSE is consistent with the results that I obtained with Mendelian randomization.
I used as exposure the SNPs that result from MR (in my case 192 -significant, strong and independent-), and all summary statistics for the outcome. 
Looking at the MR results, I2 is equal to 0 so I will expect that also CAUSE gives this information.

But the results say something different:

```
sharing is better than null > there is evidence of pleiotropy;
causal better than null> there is evidence of causality and pleiotropy;
causal better than sharing > there is evidence of causality and pleiotropy
```

Looking at the results that I obtained with MR I expected that CAUSE also gives as output no evidence of pleiotropy (due to the fact that I am using the SNPs coming from MR.)

I tried to run CAUSE with another exposure (where with MR approach there is evidence of causality) and the CAUSE's results say that there is no evidence of causality (null better than sharing; null better than causal; sharing better than causal).

I have some inconsistencies between MR and CAUSE. 

Why this is happening? Should I expect the same MR results?

Hope to be more clear, thanks

**Comment by jean997** [comment] 2023-07-19 17:38
I am not totally sure what you mean by "MR" here. CAUSE is one of many MR methods and it sounds like you are comparing with another method. However, I don't know what I2 is in your notation. 

CAUSE doesn't test whether or not there is a confounder in the causal model. This means that we never compare the model with a causal effect and a confounder to the model with a causal effect and no confounder.

You can look at the posterior distributions for more information. The parameters eta and q tell you about the pleiotropic effect. Eta is the size of the confounder effect and q is the proportion of variants acting through the confounder. If you look in the example
https://jean997.github.io/cause/ldl_cad.html#Step_5:_Look_at_Results
You can see that the posterior of eta is peaked around zero and the posterior of q is shifted close to 0 which suggests that there is not much of a confounder effect. However, we don't directly test this hypothesis.

**Comment by jean997** [comment] 2023-07-19 17:40
I am going to close this issue but you are welcome to post additional comments here. I will still see the notification even if the issue is closed.

**Closed as completed by jean997** 2023-07-19 17:40 UTC
